### ISSUE TITLE
Throws an exception on Node.js v.10.15.0

### ISSUE THREAD

**Issue by yehorbk** [HowProgrammingWorks/Mixin#4]
This line cause _"TypeError: clazz is not a constructor"_ exception:
https://github.com/HowProgrammingWorks/Mixin/blob/5339cb18e22bb1ca2c54dc21492a324c249e77bd/JavaScript/7-build.js#L116

I'm not sure, but I think that is because _**toString**_ is a property with getter (when we want to call it we use `obj.toString` instead of `obj.toString()`). Consequently there is not overrided **toString** method in **ProtoClass**.

<img width="656" alt="image" src="https://user-images.githubusercontent.com/35728917/71785354-404e5080-3007-11ea-8381-7ff4d6ce7aa5.png">

But it works **fine** on Node.js `v12.14.0`.

**Comment by tshemsedinov** [comment]
Somebody already reported and fixed this. See: https://github.com/nodejs/node/issues/25451
